server:
  port: 8082
  error:
    include-message: on-param
    whitelabel:
      enabled: false
  servlet:
    context-path: /api/v1/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skyeng_mailing
    driver-class-name: org.postgresql.Driver
    username: skyeng
    password: skyengtest
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always